# Generated by Django 4.1 on 2022-08-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=10)),
                ('nombre', models.TextField()),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('Fecha_compra', models.DateField()),
                ('Fecha_registro', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
