# Generated by Django 4.1 on 2022-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_producto_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=12)),
                ('nombre', models.TextField()),
                ('horas', models.IntegerField()),
                ('creditos', models.IntegerField()),
                ('Fecha_registro', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
